name: diversedata-notebooks
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - notebook
  - jupyterlab
  - r-base>=4.2         # the R interpreter
  - r-essentials        # common R packages + kernel
  - pip
  - pip:
    - diversedata       # Python package from PyPI/GitHub
